# Flatpak repos (System installation mode)

add = "flatpak remote-add --if-not-exists --no-gpg-verify #:?"
remove = ""

plural_name = "flatpak_repos"

hook_name = "flatpak_repos"

[config]
many_args = false
