# Flatpak repos (System installation mode nogpg)

add = "flatpak remote-add --if-not-exists --no-gpg-verify #:?"
remove = ""

plural_name = "flatpak_repos_nogpg"

hook_name = "flatpak_repos_nogpg"

[config]
many_args = false
