#Notes;

#OS_AGE record: 242 

#Software that does support wayland but needs a flag/etc;
#Wine,LibreSprite,Spotify

#Software that doesn't support wayland
#Steam > GOG + Lutris
#FFDEC > ?
#Ghidra > Cutter with ghidra decompiler
#Resolve > Kdenlive/OpenShot

#Packages to be installed via Pacman.
[managers.system]
items = [
    "zip",
    "p7zip",
    "kio-admin",
    "flatpak-builder",
    "discover",
    "distrobox",
    "lshw",
    "umu-launcher", # DO NOT REMOVE
    "mangohud", #Remove once you learn how to use the flatpak pkg from cli
    "gamemode",
    "gamescope",
    "kaccounts-providers",
    "timeshift",
    "xdg-desktop-portal-gtk",
    "vkmark",
    "wireguard-tools",
    "headscale",
    "krita-git", #Switch to universal once universal pkg comes out.
    "wine",
    "winetricks",
    "opensnitch",
    "kdialog",
    "zenity",
    "btop",
    "htop",
]
#Disabled pkgs
#"vlc-git", #Switch to universal once universal pkg comes out. //Still a headache
#archlinux-xdg-menu
#hyprland
#swaylock  #Don't use hyprlock that shits ass
#hyprshot
#hyprpaper
#waybar
#wofi
#sway
#lib32-mangohud #When not using WoW64 mode of wine (for 32bit win games)

#Packages to be installed via YaY.
[managers.yay]
items = [
    "waydroid",
    "binder_linux-dkms",
]
#flashpoint-launcher-bin

#Packages to be installed via am.
[managers.am]
items = [
    "helium",
    "heroic-games-launcher",
]

#Packages to be installed via Soar.
[managers.soar]
items = [
    "sas#AM.x86_64.sas.sas:ivan-hc-am",
    "librewolf#gitlab.com.librewolf-community.browser.appimage.stable:pkgcache",
    "fastfetch#sharun.wrappe.stable.fastfetch:pkgcache", # Don't change this, remember sound issue
    "micro#github.com.zyedidia.micro:bincache",
    "nvim#AM.x86_64.nvim.nvim:ivan-hc-am",
    "cromite#github.com.pkgforge-dev.Cromite-AppImage",
    "goverlay#github.com.benjamimgois.goverlay.stable:pkgcache",
    "waydroid-helper#github.com.ayasa520.waydroid-helper.stable:pkgcache",
]
#Disabled pkgs
#vlc-git#AM.x86_64.vlc-git.vlc-git:ivan-hc-am
#pince#AM.x86_64.pince.pince:ivan-hc-am # https://github.com/pkgforge/soarpkgs/issues/222

#Packages to be installed via Soar. (Profile 1)
[managers.soar_profile1]
items = [
    "ultimmc#wrappe.ultimmc:pkgcache",
    "inkscape#gitlab.com.inkscape.inkscape",
]

#Repos to be added system wide.
[managers.flatpak_repos]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo",
    "hero-persson https://hero-persson.github.io/unmojang-flatpak/index.flatpakrepo",
    "ykc https://flatpak.yellowkeycard.net/ykc.flatpakrepo",
]

#Repos to be added as user.
[managers.flatpak_repos_user]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo",
    "hero-persson https://hero-persson.github.io/unmojang-flatpak/index.flatpakrepo",
    "ykc https://flatpak.yellowkeycard.net/ykc.flatpakrepo",
]

#Repos to be added to the extra installation.
[managers.flatpak_repos_extra]
items = [
    "flathub https://dl.flathub.org/repo/flathub.flatpakrepo",
    "flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo",
    "hero-persson https://hero-persson.github.io/unmojang-flatpak/index.flatpakrepo",
    "ykc https://flatpak.yellowkeycard.net/ykc.flatpakrepo",
]

#Repos to be added to the extra installation. NoGPG
[managers.flatpak_repos_user_nogpg]
items = [
    "funkin-flatpak https://pucas01.github.io/Funkin-Flatpak/",
]

# Packages to be installed via Flatpak. (System mode)
#[managers.flatpak]
#items = [
#    "", #Placeholder since I don't need to install anything as system?
#]

# Packages to be installed via Flatpak. (User mode)
[managers.flatpak_user]
items = [
    "flathub dev.zed.Zed",
    "flathub org.ghidra_sre.Ghidra",
    "flathub org.gnome.Calculator",
    "flathub org.filezillaproject.Filezilla",
    "flathub com.spotify.Client",
    "flathub org.strawberrymusicplayer.strawberry",
    "flathub website.i2pd.i2pd",
    "flathub dev.deedles.Trayscale",
    "flathub flathub com.github.ztefn.haguichi",
    "flathub com.heroicgameslauncher.hgl",
    "flathub org.gnome.Boxes",
    "flathub io.github.giantpinkrobots.varia",
    "flathub im.nheko.Nheko",
    "flathub im.riot.Riot",
    "flathub org.signal.Signal",
    "flathub dev.vencord.Vesktop",
    "flathub io.github.flattool.Warehouse",
    "flathub com.rustdesk.RustDesk",
    "flathub net.werwolv.ImHex",
    "flathub rs.ruffle.Ruffle",
    "flathub org.gimp.GIMP",
    "flathub io.gitlab.theevilskeleton.Upscaler",
    "flathub io.github.martinrotter.rssguard",
    "flathub org.kde.kclock",
    "flathub org.kde.filelight",
    "flathub org.libreoffice.LibreOffice",
    "flathub org.kde.okular",
    "flathub org.nickvision.tubeconverter",
    "flathub com.obsproject.Studio",
    "flathub com.dec05eba.gpu_screen_recorder",
    "flathub org.shotcut.Shotcut",
    "flathub org.kde.kdenlive",
    "flathub com.valvesoftware.Steam",
    "flathub org.libretro.RetroArch",
    "flathub com.vysp3r.ProtonPlus",
    "flathub com.github.Matoking.protontricks",
    "flathub org.freedesktop.Platform.VulkanLayer.MangoHud",
    "flathub org.freedesktop.Platform.VulkanLayer.gamescope",
    "hero-persson org.unmojang.FjordLauncher",
    "funkin-flatpak io.github.Pucas01.FunkinFlatpak",
]
#"flathub net.lutris.Lutris", # Lutris is still dead
#"flathub re.rizin.cutter",
#"flathub re.rizin.cutter.plugin.rz-ghidra",
#"flathub org.freedesktop.Platform.VulkanLayer.vkBasalt",


# Packages to be installed via Flatpak. (Extra mode)
[managers.flatpak_extra]
items = [
    "flathub io.mrarm.mcpelauncher",
    "flathub sh.ppy.osu",
    "flathub tw.ddnet.ddnet",
    "flathub org.zdoom.GZDoom",
    "flathub net.supertuxkart.SuperTuxKart",
    "flathub dev.bragefuglseth.Keypunch",
    "flathub io.github.TheWisker.Cavasik",
    "flathub com.github.tchx84.Flatseal",
    "flathub io.github.marco_calautti.DeltaPatcher",
    "flathub com.jpexs.decompiler.flash",
    "flathub org.kde.haruna",
    "flathub io.mpv.Mpv",
    "flathub io.github.peazip.PeaZip",
    "flathub org.qbittorrent.qBittorrent",
    "flathub org.tenacityaudio.Tenacity",
    "flathub org.vinegarhq.Sober",
]
#    "flathub ch.openboard.OpenBoard",

# Packages to be installed as .flatpak files.
#[managers.flatpak_file]
#items = [
    #"github.com/3ster/ida-freeware-flatpak"
    #"gitgud.io/Twig6943/resolve-flatpak",
    #"github.com/fn2006/PollyMC",
    #"github.com/unmojang/FjordLauncher"
    #"github.com/Pucas01/FunkinFlatpak",
#]
