begin = [
  "system",
  "yay",
  "am",
  "soar",
  "soar_profile1",
]

end = [
  "flatpak_repos",
  "flatpak_repos_user",
  "flatpak_repos_extra",
  "flatpak_repos_user_nogpg",
  "flatpak_user",
  "flatpak_extra",
]
