# A list of apps categorized by their source platform

F-Droid.repos = [
 "microg.org/fdroid/repo",
 "cromite.org/fdroid/repo",
 "www.collaboraoffice.com/downloads/fdroid/repo/?fingerprint=573258C84E149B5F4D9299E7434B2B69A8410372921D4AE586BA91EC767892CC",
 "apt.izzysoft.de/fdroid/repo",
 "mobileapp.bitwarden.com/fdroid/repo",
]

F-Droid = [
 "org.microg.gms",
 "com.nextcloud.client",
 "it.niedermann.owncloud.notes",
 "com.nononsenseapps.notepad",
 "org.schabi.newpipe",
 "org.purplei2p.i2pd",
 "com.stoutner.privacybrowser.standard",
 "com.aurora.store",
 "co.prestosole.clima",
 "im.vector.app",
 "com.zaneschepke.wireguardautotunnel",
 "org.documentfoundation.libreoffice",
 "dev.imranr.obtainium.fdroid",
 "com.foobnix.pro.pdf.reader",
 "com.secuso.privacyFriendlyCodeScanner",
 "com.nononsenseapps.feeder",
 "org.ca.squawker",
 "com.beemdevelopment.aegis",
 "me.zhanghai.android.files",
 "us.spotco.fennec_dos",
 "com.retroarch",
 "is.xyz.mpv",
 "org.videolan.vlc",
 "de.yaacc",
 "org.joinmastodon.android",
 "com.commit451.gitlab",
 "org.cromite.cromite",
 "com.collabora.libreoffice",
 "com.hjiangsu.thunder",
 "com.x8bit.bitwarden",
]
#Disabled pkgs;

Obtanium = [
 "github.com/bluesky-social/social-app",
 "github.com/flixclusiveorg/Flixclusive",
 "github.com/revoltchat/rvmob",
 "github.com/ruffle-rs/ruffle-android",
 "github.com/signalapp/Signal-Android",
 "github.com/KhoalaS/Infinity-For-Reddit",
 "github.com/NewPipeX/NewPipeX",
 "github.com/ProtonMail/android-mail",
 "github.com/karlstav/cava",
 "whatsapp get from apps.obtainium.imranr.dev",
 "torproject.org/download CALF:tor-browser-android-aarch64.*apk$",
]
#CALF=Custom apk link filter for Obtanium
#Disabled pkgs
#

Play_Store = [
 "",
]
#Disabled pkgs
#com.whatsapp
