arch = {
  packages = [
    "zip",
    "7zip",
    "msedit",
    "kio-admin",
    "flatpak-builder",
    "wl-clipboard", # This is for vi and vim
    "discover",
    "distrobox",
    "lshw",
    "zerotier-one",
    "waydroid",
    "binder_linux-dkms",
    "wps-office-cn",
    "umu-launcher", # DO NOT REMOVE
    "mangohud", #Remove once you learn how to use the flatpak pkg from cli
    "gamemode",
    "gamescope",
    "kaccounts-providers",
    "timeshift",
    "xdg-desktop-portal-gtk",
    "vkmark",
    "wireguard-tools",
    "headscale",
    "krita-git", #Switch to universal once universal pkg comes out.
    "wine",
    "winetricks",
    "opensnitch",
    "kdialog",
    "zenity",
    "btop",
    "htop",
  ]
}

flatpak = {
  repos = [
    # flathub
    { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/flathub.flatpakrepo" } },
    { name = "user:flathub", options = { url = "https://dl.flathub.org/repo/flathub.flatpakrepo" } },
    { name = "extra:flathub", options = { url = "https://dl.flathub.org/repo/flathub.flatpakrepo" } },
    # flathub beta
    { name = "system:flathub-beta", options = { url = "https://flathub.org/beta-repo/flathub-beta.flatpakrepo" } },
    { name = "user:flathub-beta", options = { url = "https://flathub.org/beta-repo/flathub-beta.flatpakrepo" } },
    { name = "extra:flathub-beta", options = { url = "https://flathub.org/beta-repo/flathub-beta.flatpakrepo" } },
    # hero-persson
    { name = "system:hero-persson", options = { url = "https://hero-persson.github.io/unmojang-flatpak/index.flatpakrepo" } },
    { name = "user:hero-persson", options = { url = "https://hero-persson.github.io/unmojang-flatpak/index.flatpakrepo" } },
    { name = "extra:hero-persson", options = { url = "https://hero-persson.github.io/unmojang-flatpak/index.flatpakrepo" } },
    # ykc
    { name = "system:ykc", options = { url = "https://flatpak.yellowkeycard.net/ykc.flatpakrepo" } },
    { name = "user:ykc", options = { url = "https://flatpak.yellowkeycard.net/ykc.flatpakrepo" } },
    { name = "extra:ykc", options = { url = "https://flatpak.yellowkeycard.net/ykc.flatpakrepo" } },
  ],
  packages = [
    # user
    { name = "user:dev.zed.Zed", options = { remote = "flathub" } },
    { name = "user:org.ghidra_sre.Ghidra", options = { remote = "flathub" } },
    { name = "user:org.gnome.Calculator", options = { remote = "flathub" } },
    { name = "user:org.filezillaproject.Filezilla", options = { remote = "flathub" } },
    { name = "user:com.spotify.Client", options = { remote = "flathub" } },
    { name = "user:org.strawberrymusicplayer.strawberry", options = { remote = "flathub" } },
    { name = "user:website.i2pd.i2pd", options = { remote = "flathub" } },
    { name = "user:org.gnome.Boxes", options = { remote = "flathub" } },
    { name = "user:io.github.giantpinkrobots.varia", options = { remote = "flathub" } },
    { name = "user:io.github.BrisklyDev.Brisk", options = { remote = "flathub" } }, # Keep ts as backup
    { name = "user:im.nheko.Nheko", options = { remote = "flathub" } },
    { name = "user:im.riot.Riot", options = { remote = "flathub" } },
    { name = "user:org.signal.Signal", options = { remote = "flathub" } },
    { name = "user:dev.vencord.Vesktop", options = { remote = "flathub" } },
    { name = "user:io.github.flattool.Warehouse", options = { remote = "flathub" } },
    { name = "user:com.rustdesk.RustDesk", options = { remote = "flathub" } },
    { name = "user:net.werwolv.ImHex", options = { remote = "flathub" } },
    { name = "user:rs.ruffle.Ruffle", options = { remote = "flathub" } },
    { name = "user:org.gimp.GIMP", options = { remote = "flathub" } },
    { name = "user:io.gitlab.theevilskeleton.Upscaler", options = { remote = "flathub" } },
    { name = "user:io.github.martinrotter.rssguard", options = { remote = "flathub" } },
    { name = "user:org.kde.kclock", options = { remote = "flathub" } },
    { name = "user:org.kde.filelight", options = { remote = "flathub" } },
    { name = "user:org.libreoffice.LibreOffice", options = { remote = "flathub" } },
    { name = "user:org.kde.okular", options = { remote = "flathub" } },
    { name = "user:org.nickvision.tubeconverter", options = { remote = "flathub" } },
    { name = "user:com.obsproject.Studio", options = { remote = "flathub" } },
    { name = "user:com.dec05eba.gpu_screen_recorder", options = { remote = "flathub" } },
    { name = "user:org.shotcut.Shotcut", options = { remote = "flathub" } },
    { name = "user:org.kde.kdenlive", options = { remote = "flathub" } },
    { name = "user:com.heroicgameslauncher.hgl", options = { remote = "flathub" } },
    { name = "user:com.valvesoftware.Steam", options = { remote = "flathub" } },
    { name = "user:org.libretro.RetroArch", options = { remote = "flathub" } },
    { name = "user:com.vysp3r.ProtonPlus", options = { remote = "flathub" } },
    { name = "user:com.github.Matoking.protontricks", options = { remote = "flathub" } },
    { name = "user:org.freedesktop.Platform.VulkanLayer.MangoHud", options = { remote = "flathub" } },
    { name = "user:org.freedesktop.Platform.VulkanLayer.gamescope", options = { remote = "flathub" } },
    #{ name = "user:io.github.Pucas01.FunkinFlatpak", options = { remote = "funkin-flatpak" } }, #requires nogpg
    # extra
    { name = "extra:org.unmojang.FjordLauncher", options = { remote = "hero-persson" } },
    { name = "extra:io.mrarm.mcpelauncher", options = { remote = "flathub" } },
    { name = "extra:org.vinegarhq.Sober", options = { remote = "flathub" } },
    { name = "extra:sh.ppy.osu", options = { remote = "flathub" } },
    { name = "extra:tw.ddnet.ddnet", options = { remote = "flathub" } },
    { name = "extra:org.zdoom.GZDoom", options = { remote = "flathub" } },
    { name = "extra:net.supertuxkart.SuperTuxKart", options = { remote = "flathub" } },
    { name = "extra:dev.bragefuglseth.Keypunch", options = { remote = "flathub" } },
    { name = "extra:io.github.TheWisker.Cavasik", options = { remote = "flathub" } },
    { name = "extra:com.github.polymeilex.neothesia", options = { remote = "flathub" } },
    { name = "extra:net.sourceforge.VMPK", options = { remote = "flathub" } },
    { name = "extra:com.github.tchx84.Flatseal", options = { remote = "flathub" } },
    { name = "extra:io.github.marco_calautti.DeltaPatcher", options = { remote = "flathub" } },
    { name = "extra:com.jpexs.decompiler.flash", options = { remote = "flathub" } },
    { name = "extra:io.mpv.Mpv", options = { remote = "flathub" } },
    { name = "extra:org.qbittorrent.qBittorrent", options = { remote = "flathub" } },
    { name = "extra:org.tenacityaudio.Tenacity", options = { remote = "flathub" } },
  ]
}

# Packages to be installed as .flatpak files.
#[managers.flatpak_file]
#items = [
    #"github.com/3ster/ida-freeware-flatpak"
    #"gitgud.io/Twig6943/resolve-flatpak",
    #"github.com/fn2006/PollyMC",
    #"github.com/unmojang/FjordLauncher"
    #"github.com/Pucas01/FunkinFlatpak"
