arch = [
    "zip",
    "7zip",
    "msedit",
    "kio-admin",
    "flatpak-builder",
    "wl-clipboard", # This is for vi and vim
    "discover",
    "distrobox",
    "lshw",
    "zerotier-one",
    "waydroid",
    "binder_linux-dkms",
    "wps-office-cn",
    "umu-launcher", # DO NOT REMOVE
    "mangohud", #Remove once you learn how to use the flatpak pkg from cli
    "gamemode",
    "gamescope",
    "kaccounts-providers",
    "timeshift",
    "xdg-desktop-portal-gtk",
    "vkmark",
    "wireguard-tools",
    "headscale",
    "krita-git", #Switch to universal once universal pkg comes out.
    "wine",
    "winetricks",
    "opensnitch",
    "kdialog",
    "zenity",
    "btop",
    "htop",
]
flatpak = [
    # User
    "dev.zed.Zed", "user", "flathub",
    "org.ghidra_sre.Ghidra", "user", "flathub",
    "org.gnome.Calculator", "user", "flathub",
    "org.filezillaproject.Filezilla", "user", "flathub",
    "com.spotify.Client", "user", "flathub",
    "org.strawberrymusicplayer.strawberry", "user", "flathub",
    "website.i2pd.i2pd", "user", "flathub",
    "org.gnome.Boxes", "user", "flathub",
    "io.github.giantpinkrobots.varia", "user", "flathub",
    "io.github.BrisklyDev.Brisk", "user", "flathub", # Keep ts as backup
    "im.nheko.Nheko", "user", "flathub",
    "im.riot.Riot", "user", "flathub",
    "org.signal.Signal", "user", "flathub",
    "dev.vencord.Vesktop", "user", "flathub",
    "io.github.flattool.Warehouse", "user", "flathub",
    "com.rustdesk.RustDesk", "user", "flathub",
    "net.werwolv.ImHex", "user", "flathub",
    "rs.ruffle.Ruffle", "user", "flathub",
    "org.gimp.GIMP", "user", "flathub",
    "io.gitlab.theevilskeleton.Upscaler", "user", "flathub",
    "io.github.martinrotter.rssguard", "user", "flathub",
    "org.kde.kclock", "user", "flathub",
    "org.kde.filelight", "user", "flathub",
    "org.libreoffice.LibreOffice", "user", "flathub",
    "org.kde.okular", "user", "flathub",
    "org.nickvision.tubeconverter", "user", "flathub",
    "com.obsproject.Studio", "user", "flathub",
    "com.dec05eba.gpu_screen_recorder", "user", "flathub",
    "org.shotcut.Shotcut", "user", "flathub",
    "org.kde.kdenlive", "user", "flathub",
    "com.heroicgameslauncher.hgl", "user", "flathub",
    "com.valvesoftware.Steam", "user", "flathub",
    "org.libretro.RetroArch", "user", "flathub",
    "com.vysp3r.ProtonPlus", "user", "flathub",
    "com.github.Matoking.protontricks", "user", "flathub",
    "org.freedesktop.Platform.VulkanLayer.MangoHud", "user", "flathub",
    "org.freedesktop.Platform.VulkanLayer.gamescope", "user", "flathub",
    "org.unmojang.FjordLauncher", "user", "hero-persson",
    "io.github.Pucas01.FunkinFlatpak", "user", "funkin-flatpak",
    # Extra
    "io.mrarm.mcpelauncher", "extra", "funkin-flatpak",
    "sh.ppy.osu", "extra", "funkin-flatpak",
    "tw.ddnet.ddnet", "extra", "funkin-flatpak",
    "org.zdoom.GZDoom", "extra", "funkin-flatpak",
    "net.supertuxkart.SuperTuxKart", "extra", "funkin-flatpak",
    "dev.bragefuglseth.Keypunch", "extra", "funkin-flatpak",
    "io.github.TheWisker.Cavasik", "extra", "funkin-flatpak",
    "com.github.polymeilex.neothesia", "extra", "funkin-flatpak",
    "net.sourceforge.VMPK", "extra", "funkin-flatpak",
    "com.github.tchx84.Flatseal", "extra", "funkin-flatpak",
    "io.github.marco_calautti.DeltaPatcher", "extra", "funkin-flatpak",
    "com.jpexs.decompiler.flash", "extra", "funkin-flatpak",
    "io.mpv.Mpv", "extra", "funkin-flatpak",
    "io.github.peazip.PeaZip", "extra", "funkin-flatpak",
    "org.qbittorrent.qBittorrent", "extra", "funkin-flatpak",
    "org.tenacityaudio.Tenacity", "extra", "funkin-flatpak",
    "org.vinegarhq.Sober", "extra", "funkin-flatpak",
]


