arch = [
  "package1",
  { package = "package2" },

  { package = "openssh", hooks = { after_sync = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "sshd",
  ] } },
  { package = "fastfetch", hooks = { before_install = [
    "echo",
    "before_install",
  ], after_install = [
    "echo",
    "after_install",
  ], before_sync = [
    "echo",
    "before_sync",
  ], after_sync = [
    "echo",
    "after_sync",
  ] } },
]
flatpak = [
  "package1",
  { package = "package2", options = { remote = "flathub", systemwide = false } },
]
