# This toml file is here just for reference.

# Default wrapper
flatpak-spawn --no-network --env=PROTONPATH=/home/twig/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools/proton/GE-Proton-latest/ --env=PROTON_ENABLE_WAYLAND=1 --env=WINEPREFIX=/mnt/09403f3c-3c66-47f2-a0b4-5b5fbae04d23/home/twig/Games/DefaultPrefix/
